name: Deploy to AWS EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Debug SSH Connection
      run: ssh -v -o StrictHostKeyChecking=no -i "c:\Users\Samarth\Downloads\isl_key.pem" ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i c:\Users\Samarth\Downloads\isl_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd isl_backend
          git pull origin master
          source venv/bin/activate
          pip install -r requirements.txt
          nohup uvicorn main:app --host 0.0.0.0 --port 8000 --reload > backend.log 2>&1 &

          cd ~/isl_frontend
          git pull origin master
          source venv/bin/activate
          pip install -r requirements.txt
          nohup streamlit run app.py --server.port 8501 --server.address 0.0.0.0 > frontend.log 2>&1 &
        EOF
